# Кэширование на основе Content-Type
map $sent_http_content_type $expires {
    default                    off;
    text/html                  epoch;
    text/css                   max;
    application/javascript     max;
    application/wasm           max;
}
